{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
{{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.httpRoute.hostnames }}
  hostnames:
{{ toYaml . | nindent 4 }}
  {{- end }}

  rules:
{{ toYaml .Values.httpRoute.rules | nindent 4 }}
{{- end }}

